include: https://gitlab.com/TouchBIT/gitlab-ci/raw/master/common.yml

TestRail4J:
  extends: .build_java_project
  after_script:
    - mv testrail4j-integration-tests/target/Corvus.jar Corvus.jar
  artifacts:
    paths:
      - Corvus.jar
    expire_in: 30 days

Sphinx doc:
  extends: .build_sphinx_doc

JUnit:
  extends: .junit_test_run

Integration:
  dependencies:
    - TestRail4J
  stage: test
  tags:
    - touchbit-shell
  variables:
    ARTIFACTS_URL: "${CI_PROJECT_URL}/-/jobs/$CI_JOB_ID/artifacts/file/"
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - export TR_HTTP_PORT=$(shuf -i10000-60000 -n1)
    - export TR_HTTPS_PORT=$(shuf -i10000-60000 -n1)
  script:
    - make docker-up
    - java -jar Corvus.jar --artifacts-url ${ARTIFACTS_URL} --http-port ${TR_HTTP_PORT} --https-port ${TR_HTTPS_PORT}
  after_script:
    - make docker-logs
    - make docker-down
  artifacts:
    when: always
    paths:
      - logs
    expire_in: 30 days

Sonar review:
  extends: .sonar_review
  dependencies:
    - JUnit

Release:
  extends: .trigger_release_deploy

Snapshot:
  extends: .trigger_snapshot_deploy

Clean runner:
  stage: clean
  only:
    - schedules
  tags:
    - touchbit-shell
  script:
    - make docker-clean