stages:
  - build
  - test
  - verify
  - deploy

.docker_image_build_push:
  stage: build
  tags:
    - touchbit-shell
  variables:
    REGISTRY_IMAGE:
    DOCKERFILE:
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - docker build -f ${DOCKERFILE} -t ${REGISTRY_IMAGE} .
    - docker push ${REGISTRY_IMAGE}

Integration:
  stage: test
  tags:
    - touchbit-shell
  image: docker-compose:latest
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose -f .indirect/docker-compose.yml kill &
    - docker-compose -f .indirect/docker-compose.yml pull
    - docker-compose -f .indirect/docker-compose.yml up -d
