version: "3"

volumes:
  static-content:

services:

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: 1234
      SKIP_GRANT_TABLES: 1
      SKIP_NETWORKING: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  migration:
    image: registry.gitlab.com/touchbit/image/testrail/migration:latest
    links:
    - db
    depends_on:
    - db

  fpm:
    image: registry.gitlab.com/touchbit/image/testrail/fpm:latest
    volumes:
    - static-content:/var/www/testrail
    links:
    - db

  web:
    image: registry.gitlab.com/touchbit/image/testrail/web:latest
    ports:
    - ${TR_HTTP_PORT:-80}:80
    - ${TR_HTTPS_PORT:-443}:443
    volumes:
    - static-content:/var/www/testrail
    links:
    - db
    - fpm