name: Testrail4J

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - '*'
    paths-ignore:
      - README.rst
      - LICENSE.rst
      - Makefile

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      SONAR_GH_CI_TOKEN: ${{ secrets.SONAR_GH_CI_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: sonatype
          server-username: SONATYPE_LOGIN
          server-password: SONATYPE_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Init m2 cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build & test
        run: mvn clean package
      - if: github.ref == 'refs/heads/master' || github.event_name == 'release'
        name: Sonar master/release rewiew
        run: mvn package sonar:sonar -DskipTests=true -Dsonar.login=${SONAR_GH_CI_TOKEN}
      - if: github.event_name == 'pull_request'
        name: Sonar pull request rewiew
        run: |
          mvn package sonar:sonar -DskipTests=true \
          -Dsonar.login=${SONAR_GH_CI_TOKEN} \
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
          -Dsonar.pullrequest.branch=${GITHUB_HEAD_REF} \
          -Dsonar.pullrequest.base=${GITHUB_BASE_REF}

# find ./ -type f -name *.log -exec sed -i 's/Authorization: Basic .*/Authorization: Basic <hidden>/g' {} \;