name: Maintenance

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  clear:
    runs-on: ubuntu-latest
    name: Clear
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Init m2 cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Delete testrail projects
        run: |
          mvn clean package -DskipTests=true
          cp testrail4j-integration-tests/target/Buggy.jar ./
          java -jar Buggy.jar \
          --host ${{ secrets.TR_HOST }} \
          --login ${{ secrets.TR_LOGIN }} \
          --token ${{ secrets.TR_TOKEN }} \
          --password ${{ secrets.TR_PASSWORD }} \
          -s MAINTENANCE
